### ISSUE TITLE
Namespace 'global.JSX' has no exported member 'Element'.

### ISSUE THREAD

**Issue by kodeine** [Aaron-Sterling/time-ago-web-component#1]
i am getting the following error when i added the component, any idea's? do i need to install tsx support that wasnt mentioned in install docs?

<img width="873" alt="screen shot 2018-02-13 at 11 18 06 pm" src="https://user-images.githubusercontent.com/8620059/36188801-33e83c52-1114-11e8-904d-49f7321a4bac.png">

**Comment by kodeine** [comment]
i added the import, `import 'time-ago-web-component';` in app.module.ts and the component module i was using this timeago and then it works. i wonder why it doesnt work with just adding to the components module?

**Comment by Aaron-Sterling** [comment]
This looks like an issue that came up in a recent Stencil update, let me take a look. Thanks for opening the issue!

**Comment by Aaron-Sterling** [comment]
Are you eagerly loading modules or lazily loading them, and did you import CUSTOM_ELEMENT_SCHEMA into your component module?

**Comment by kodeine** [comment]
I am lazily loading modules and yes I did add custom element schema

**Comment by kodeine** [comment]
I have to add import and custom element schema in app module and custom component both to make it work

**Comment by Aaron-Sterling** [comment]
I'm closing this because I think it's resolved. If you still have questions, let me know and I'll reopen. Thanks again.
