### ISSUE TITLE
amDateFormat?

### ISSUE THREAD

**Issue by kodeine** [Aaron-Sterling/time-ago-web-component#2]
Hello, can you update it with `amDateFormat:'MMMM Do, YYYY'` as well?

**Comment by Aaron-Sterling** [comment]
Next version will allow for full format modification. Coming soon.....

**Comment by Aaron-Sterling** [comment]
Should work, I tried with time="January 5, 2006" and it worked fine. Thanks for opening this issue,

**Comment by Aaron-Sterling** [comment]
Sorry, I should have mentioned: please note breaking change. The boolean property suffix is now a string property append.
